config/routes.rb
Rails.application.routes.draw do

  root 'links#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :links, only: [:index, :create, :edit, :update]
  namespace :api do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, url: {:no_local => true}

  before_validation :insert_http_prefix

  def read_button
    if read
      {label: 'Mark as Unread', class: 'btn-info'}
    else
      {label: 'Mark as Read', class: 'btn-danger'}
    end
  end

  def url_class
    read ? 'read' : 'unread'
  end

  private

    def insert_http_prefix
      self.url = 'http://' + self.url if self.url.first(7) != 'http://'
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def update
    link = Link.find_by(id: params[:id])
    response, status = if link.update(read: !link.read)
      [link, 200]
    else
      flash.notice = errors.full_messages.join(', ')
      [flash.notice, 400]
    end
    render json: response, status: status
  end

  # def index
  #   ideas = Idea.all.order('created_at ASC')
  #   respond_with Idea.new.ideas_with_tags(ideas)
  # end
  #
  # def show
  #   idea = Idea.find_by(id: params[:id])
  #   respond_with idea.idea_with_tags
  # end
  #
  # def create
  #   new_idea = Idea.new(idea_params.except("tags"))
  #   if new_idea.save
  #     save_tags(new_idea)
  #     render json: new_idea.idea_with_tags, status: 200
  #   else
  #     render json: new_idea.errors, status: 400
  #   end
  # end

  # def destroy
  #   deleted_idea = Idea.find_by(id: params[:id]).destroy
  #   if deleted_idea
  #     render json: deleted_idea, status: 200
  #   else
  #     render json: deleted_idea.errors, status: 400
  #   end
  # end

  private

    def idea_params
      params.permit(:title, :description, :tags)
    end

    # def save_tags(idea)
    #   Tag.add_new_tags(params[:tags], idea) if !params[:tags].empty?
    # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :verify_user

  def verify_user
    if !current_user
      flash.notice = "Do me a favor. Log in before you do anything else."
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login(user)
    session[:user_id] = user.id
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = current_user.links.sort
    @user_id = session[:user_id]
  end

  def create
    link = Link.new(link_params)
    if link.save
      flash.notice = "Added one more to the pile!"
      redirect_to links_path
    else
      flash.notice = "Failure! " + link.errors.full_messages.join(', ')
      redirect_to links_path
    end
  end

  def edit
    @link = Link.find_by(id: params[:id])
  end

  def update
    link = Link.find_by(id: params[:id])
    link.update(link_params)
    if !link.errors.empty?
      flash.notice = "Failure! " + link.errors.full_messages.join(', ')
    end
    redirect_to links_path
  end

  private

    def link_params
      params.require(:link).permit(:title, :url, :user_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_user, only: [:new, :create]

  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    user = User.find_by(email:  user_params[:email])
    if user && user.authenticate(user_params[:password])
      login(user)
      redirect_to links_path
    else
      flash.notice = "Invalid credentials. Try again, poser."
      redirect_to login_path
    end

  end

  def destroy
    flash.notice = "Successfully logged out. See ya next time!" if session.clear
    redirect_to login_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash.notice = "Thanks for signing up. Welcome to the club!"
      login(user)
      redirect_to root_path
    else
      flash.notice = user.errors.full_messages.join(', ')
      redirect_to signup_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/api/v1/links_helper.rb
module Api::V1::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    session[:user_id]
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to "ThoughtBox", '/', id: 'logo' %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if !logged_in? %>
            <li><%= link_to "Log In", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% else %>
            <li><%=  %></li>
            <li><%= link_to "Sign Out", logout_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

<div class='container'>
  <%= flash.notice %>
  <%= yield %>
</div>

</body>
</html>

app/views/links/edit.html.erb
<h1 class='text-center'>Edit Your Link</h1>

<div>
  <%= form_for(:link, url: @link, method: :patch) do |f| %>
    <%= f.text_field :title, placeholder: @link.title, class: 'form-control' %>
    <%= f.text_field :url, placeholder: @link.url, class: 'form-control' %>
    <%= f.submit 'Edit link', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/links/index.html.erb
<h1 class='text-center'>Your Links</h1>

<div>
  <h2>Add a new link</h2>
  <%= form_for(:link, url: links_path) do |f| %>
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    <%= f.text_field :url, placeholder: 'URL', class: 'form-control' %>
    <%= f.hidden_field :user_id, value: @user_id %>
    <%= f.submit 'Add to your list', class: 'btn btn-primary' %>
  <% end %>
</div>

<div>
  <% @links.each do |link| %>
    <hr>
    <div class="link <%= link.url_class %>" id=<%= link.id %>>
      <h2>Link #<%= link.id %>: <%= link.title %> <%= link_to "Edit", edit_link_path(link), class: 'btn btn-success' %></h2>
      <h3><%= link_to link.url, link.url, class: "url" %> <button class="btn <%= link.read_button[:class] %> read-button"><%= link.read_button[:label] %></button></h3>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>

<div>
  <%= form_for(:user, url: signup_path) do |f| %>
    <%= f.text_field :email, placeholder: 'email', class: 'form-control' %>
    <%= f.password_field :password, placeholder: 'password', class: 'form-control' %>
    <%= f.password_field :password_confirmation, placeholder: 'confirm password', class: 'form-control' %>
    <%= f.submit 'Signup', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>ThoughtBox</h1>